/* EXT_INTERRUPT_Config.h */

/* EXT_INTERRUPT_Config.h */


//INTERRUPT_SENCE_MODE
/* RISING_EDGE
 * FALLING_EDGE
 * ON_CHANGE
 * LOW_LEVEL
*/

#define INTERRUPT0_SENCE_MODE RISING_EDGE
